web = "../../images/Cake_image 1.png"
Products = [
    {
        "id": '1',
        "name": "Apple Cake",
        "rating": 5,
        "Price": "500",
        "imageurl": web,
    },
    {
        "id": '2',
        "name": "Pink Cake",
        "rating": 4.6,
        "Price": "500",
        "imageurl": web,
    },
    {
        "id": '3',
        "name": "Red Cake",
        "rating": 4.4,
        "Price": "500",
        "imageurl": web,
    },
    {
        "id": '4',
        "name": "White Cake",
        "rating": 4,
        "Price": "500",
        "imageurl": web,
    },
    {
        "id": '5',
        "name": "Orange Cake",
        "rating": 3.7,
        "Price": "500",
        "imageurl": web,
    },
    {
        "id": '6',
        "name": "Blue Cake",
        "rating": 3.4,
        "Price": "500",
        "imageurl": web,
    },
    {
        "id": '7',
        "name": "Watermelon Cake",
        "rating": 3,
        "Price": "500",
        "imageurl": web,
    },
    {
        "id": '8',
        "name": "Apple Cake",
        "rating": 2.7,
        "Price": "500",
        "imageurl": web,
    },
    {
        "id": '9',
        "name": "Apple Cake",
        "rating": 2.4,
        "Price": "500",
        "imageurl": web,
    },
    {
        "id": '10',
        "name": "Apple Cake",
        "rating": 2,
        "Price": "500",
        "imageurl": web,
    },
    {
        "id": '11',
        "name": "Apple Cake",
        "rating": 1.7,
        "Price": "500",
        "imageurl": web,
    },
    {
        "id": '12',
        "name": "Mango Cake",
        "rating": 0.7,
        "Price": "500",
        "imageurl": web,
    },
]
