# Generated by Django 3.2 on 2021-06-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='size',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
