# Generated by Django 3.2 on 2021-08-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210801_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
